[build]
# Specify the directory to publish (root directory for CDN assets)
publish = "."

[build.environment]
# Set Node.js version if needed
NODE_VERSION = "18"

[[headers]]
# Apply CORS headers to all files
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"

[[headers]]
# Cache static assets for 1 year
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
# Cache images for 1 month
for = "*.jpg"
[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
for = "*.jpeg"
[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
for = "*.gif"
[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
for = "*.webp"
[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
for = "*.svg"
[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
# Cache CSS and JS for 1 month with revalidation
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=2592000, must-revalidate"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=2592000, must-revalidate"

[[headers]]
# Cache fonts for 1 year
for = "*.woff"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.woff2"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.ttf"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.otf"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Custom 404 page (optional)
[[redirects]]
from = "/*"
to = "/404.html"
status = 404
